// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN10JuA06lIgdLY2cdmOR2VrKVC1A6w0Q',
    appId: '1:221128159498:web:84bb9052a28ca2c4a34af3',
    messagingSenderId: '221128159498',
    projectId: 'mochavista-82bbb',
    authDomain: 'mochavista-82bbb.firebaseapp.com',
    storageBucket: 'mochavista-82bbb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXIphlpHe9zC_TpD6X2C9LgqRvxMtMKqQ',
    appId: '1:221128159498:android:3c69e71928b85940a34af3',
    messagingSenderId: '221128159498',
    projectId: 'mochavista-82bbb',
    storageBucket: 'mochavista-82bbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZbUYZdc8JPYNFpskaNPB7vOSb9RqDw7E',
    appId: '1:221128159498:ios:becaa71e9f5f6d67a34af3',
    messagingSenderId: '221128159498',
    projectId: 'mochavista-82bbb',
    storageBucket: 'mochavista-82bbb.firebasestorage.app',
    iosBundleId: 'com.example.mochaVista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZbUYZdc8JPYNFpskaNPB7vOSb9RqDw7E',
    appId: '1:221128159498:ios:becaa71e9f5f6d67a34af3',
    messagingSenderId: '221128159498',
    projectId: 'mochavista-82bbb',
    storageBucket: 'mochavista-82bbb.firebasestorage.app',
    iosBundleId: 'com.example.mochaVista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN10JuA06lIgdLY2cdmOR2VrKVC1A6w0Q',
    appId: '1:221128159498:web:f988765b4565dc4ba34af3',
    messagingSenderId: '221128159498',
    projectId: 'mochavista-82bbb',
    authDomain: 'mochavista-82bbb.firebaseapp.com',
    storageBucket: 'mochavista-82bbb.firebasestorage.app',
  );
}
